name: Build and Release Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List dist contents
        run: ls -la dist/

      - name: Zip dist folder contents only
        run: cd dist && zip -r ../OAuth-Connections-Viewer.zip . && cd ..

      - name: List files before release
        run: ls -la *.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: OAuth-Connections-Viewer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
